build-core-stage:
  image: docker:dind
  stage: build
  tags:
    - docker
  environment:
    name: stage-build-core
    url: https://nft-seller.meta-forest.stage.dev.metafora.dev
  services:
    - docker:dind
  variables:
    SERVICE: "core"
  script:
    - "./bin/docker-registry-login.sh"
    - "./bin/docker-image-build.sh"
    - "./bin/docker-image-push.sh"
