deploy-stage:
  image: lotygerodistribution/docker-compose
  stage: deploy
  tags:
    - docker
  environment:
    name: stage-deploy
    url: https://meta-forest.stage.dev.metafora.dev
  variables:
    COMPOSE_TEMP_PATH: ".tmp"

    DOCKER_SWARM_HOST: "${DOCKER_SWARM_HOST}"

    META_FOREST_NFT_SELLER_DB_PASSWORD: "${META_FOREST_NFT_SELLER_DB_PASSWORD}"
    META_FOREST_NFT_SELLER_BOT_TOKEN: "${META_FOREST_NFT_SELLER_BOT_TOKEN}"
    META_FOREST_NFT_SELLER_TONWEB_API_KEY: "${META_FOREST_NFT_SELLER_TONWEB_API_KEY}"
    META_FOREST_NFT_SELLER_CIPHER_SALT: "${META_FOREST_NFT_SELLER_CIPHER_SALT}"
    META_FOREST_NFT_SELLER_WALLET_ADDR: "${META_FOREST_NFT_SELLER_WALLET_ADDR}"

  script:
    - "./bin/docker-compose-render.sh"
    - "./bin/docker-registry-login.sh"
    - "./bin/docker-compose-pull.sh"
    - "./bin/docker-swarm-networks.sh"
    - "./bin/docker-swarm-deploy.sh"
