---
version: "3.8"
services:
  core:
    image: "dr.metafora.dev/meta-forest/nft-seller/core/none:latest"
    pull_policy: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.meta-forest-nft-seller-core.loadbalancer.server.port=3000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 1024M
          cpus: '0.50'
        reservations:
          cpus: '0.10'
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.meta-forest-nft-seller-core.loadbalancer.server.port=3000"
    environment:
      - DB_DATABASE
      - DB_HOST
      - DB_PORT
      - DB_PASSWORD
      - DB_USER
      ##
      - BOT_TOKEN
      - PRIVATE_CHAT_ID
      - WALLET_ADDR
      - TONWEB_API_KEY
      - CIPHER_SALT

    networks:
      meta-forest:
        aliases:
          - meta-forest-nft-seller-core
      meta-forest-nft-seller:
        aliases:
          - meta-forest-nft-seller-core
      meta-forest_ext:
        aliases:
          - meta-forest-nft-seller-core

networks:

  meta-forest:
    external: true
    name: meta-forest

  meta-forest-nft-seller:
    external: true
    name: meta-forest-nft-seller

  meta-forest_ext:
    external: true
    name: meta-forest_ext
...
