---
version: "3.8"
services:
  core:
    image: "dr.metafora.dev/meta-forest/bot-subscription-checker/core/production:latest"
    environment:
      - "DB_HOST=172.18.0.1"
      - "DB_USER=meta-forest-bot-subscription-checker"
      - "DB_DATABASE=meta-forest-bot-subscription-checker"
      - "DB_PORT=5432"
      - "DB_PASSWORD=${META_FOREST_BOT_SUBSCRIPTION_CHECKER_DB_PASSWORD}"
      - "BOT_TOKEN=${META_FOREST_BOT_SUBSCRIPTION_CHECKER_BOT_TOKEN}"
      - "CHAT_ID=${META_FOREST_BOT_SUBSCRIPTION_CHECKER_CHAT_ID}"
      - "ADD_CHAT_ID=${META_FOREST_BOT_SUBSCRIPTION_CHECKER_ADD_CHAT_ID}"
      - "PRIVATE_CHAT_ID=${META_FOREST_BOT_SUBSCRIPTION_CHECKER_PRIVATE_CHAT_ID}"
    networks:
      metafora:
        aliases:
          - meta-forest-bot-subscription-checker-core

networks:
  metafora:
    external: true
    name: metafora
...
