---
version: "3.8"
services:
  core:
    image: "dr.metafora.dev/meta-forest/nft-seller/core/production:latest"
    environment:
      - "DB_HOST=172.18.0.1"
      - "DB_USER=meta-forest-nft-seller"
      - "DB_DATABASE=meta-forest-nft-seller"
      - "DB_PORT=5432"
      - "DB_PASSWORD=${META_FOREST_NFT_SELLER_DB_PASSWORD}"
      - "BOT_TOKEN=${META_FOREST_NFT_SELLER_BOT_TOKEN}"
      - "PRIVATE_CHAT_ID=${META_FOREST_NFT_SELLER_PRIVATE_CHAT_ID}"
      - "WALLET_ADDR=${META_FOREST_NFT_SELLER_WALLET_ADDR}"
      - "TONWEB_API_KEY=${META_FOREST_NFT_SELLER_TONWEB_API_KEY}"
      - "CIPHER_SALT=${META_FOREST_NFT_SELLER_CIPHER_SALT}"
    networks:
      metafora:
        aliases:
          - meta-forest-nft-seller-core

networks:
  metafora:
    external: true
    name: metafora
...
