---
version: "3.8"
services:
  core:
    image: "dr.metafora.dev/meta-forest/nft-seller/core/stage:latest"
    networks:
      metafora:
        aliases:
          - meta-forest-nft-seller-core

networks:
  metafora:
    external: true
    name: metafora
...
